apiVersion: apps/v1
kind: Deployment 
metadata:
  name: nginx
  labels: # these are replicaset labels
    app: nginx 
    tier: frontend
spec:
# modify replicas according to your requirement
  replicas: {{ .Value.deployment.replicas }}
  selector:
    matchLabels:  # these are used to select the pod to create replicas
      app: nginx
      tier: frontend
  template: # this is pod defination
    metadata:
      labels: # these labels belongs to pod
        app: nginx 
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:{{ .Value.deployment.imageVersion }}
