apiVersion: v1 
kind: Service 
metadata:
  name: nginx 
spec: 
  type: {{ .Values.service.type }}
  selector:
    app: frontend
    tier: nginx
  ports:
  - name: nginx-svc-port 
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 80 